on: 
  push:
    tags:
    - '*'

name: Release

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
    - name: Install Dependencies
      run: flutter pub get
    - name: Build
      run: flutter build apk --debug --split-per-abi
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
