on: 
  push:
    tags:
    - '*'

name: Release

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get
    - name: Build
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
